nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
    allow_credentials: false
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: []
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/': ~
